# Copyright Contributors to the Open Cluster Management project
{{- if include "dynamicPlugins.supported" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "console.fullname" . }}
  labels:
    app: {{ template "console.name" . }}
    chart: {{ template "console.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
    component: serviceaccount
{{- end -}}
