# Copyright Contributors to the Open Cluster Management project
{{- if include "dynamicPlugins.supported" . }}
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: mce
spec:
  displayName: Red Hat MultiCluster Engine
  proxy:
    - type: Service
      alias: console
      service:
        name: {{ template "console.fullname" . }}-console
        namespace: {{ .Release.Namespace }}
        port: 3000
      authorize: true
  service:
    basePath: /plugin/
    name: {{ template "console.fullname" . }}-console
    namespace: {{ .Release.Namespace }}
    port: 3000
{{- end -}}
